### ISSUE TITLE
Eschew `function`

### ISSUE THREAD

**Issue by jasonkuhrt** [littlebits/code-standards-js#2]
We should enforce `=>` over `function`. In addition any function that does not have statements should be made to use implicit return syntax.

``` js
const a  = (...) => (
  ...
)
```

instead of:

``` js
const a = (...) => {
  return ...
}
```

I've been doing this already as much as possible e.g. https://github.com/littlebitselectronics/cloud-server-subscription-filter/blob/master/lib/graph-link.js and ReactJS's latest blog post http://facebook.github.io/react/blog/2015/09/10/react-v0.14-rc1.html by @spicyj uses it too. I'm very happy to see that we are going to be able to make expression-only React components in the near future, e.g.:

``` js
const Aquarium = ({species}) => (
  Tank({}, getFish(species))
)
```

**Comment by jasonkuhrt** [comment]
We will need to write a `eslint-plugin` for this as nothing exists to do this yet.

**Comment by sch** [comment]
Any reason not to use `const`s for these?

**Comment by jasonkuhrt** [comment]
Fixed thanks.

–– Edit: These examples wouldn't have passed the scrutiny of our new lint rules : )

**Comment by jasonkuhrt** [comment]
Once there is a rule for this we will use it but this issue is not actionable until then.
